project:
  type: website
  output-dir: docs
format:
  html:
    respect-user-color-scheme: true
    theme: 
      dark: [darkly, styles-dark.scss]
      light: sandstone
    header-includes: |
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css2?family=Fira+Sans" type="text/css"/>
      <link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css2?family=Fira+Code" type="text/css"/>
    mainfont: "Fira Sans"
    monofont: "Fira Code"
highlight-style: dracula
website:
  title: "Boyd Tarlinton"
  site-url: https://boyd.tarlinton.au
  favicon: favicon.ico
  navbar:
    right:
      - text: Blog
        href: listings.qmd
      - cv.qmd
      - text: "{{< iconify fa6-brands linkedin size=large >}}"
        href: https://www.linkedin.com/in/boyd-tarlinton/
      - text: "{{< iconify fa6-brands github size=large >}}"
        href: https://github.com/B0ydT/
      - text: "{{< iconify fa6-solid at size=large >}}"
        href: mailto:b2.tarlinton@qut.edu.au
      - text: "{{< iconify fa6-brands orcid size=large >}}"
        href: https://orcid.org/0000-0002-4146-7083
      - text: "{{< iconify fa6-brands google-scholar size=large >}}"
        href: https://scholar.google.com.au/citations?user=NxovQdsAAAAJ&hl=en
      - text: "{{< iconify fa6-solid rss size=large >}}"
        href: listings.xml
  google-analytics: "G-7PC836DWQK"