project:
  type: website
  output-dir: docs
format:
  html:
    theme: sandstone
website:
  title: "Boyd Tarlinton"
  navbar:
    right:
      - text: Blog
        href: listings.qmd
      - cv.qmd
      - text: "{{< iconify fa6-brands twitter size=large >}}"
        href: https://twitter.com/bioboyd
      - text: "{{< iconify fa6-brands linkedin size=large >}}"
        href: https://www.linkedin.com/in/boyd-tarlinton/
      - text: "{{< iconify fa6-brands github size=large >}}"
        href: https://github.com/B0ydT/
      - text: "{{< iconify fa6-solid at size=large >}}"
        href: mailto:b2.tarlinton@qut.edu.au
      - text: "{{< iconify fa6-brands orcid size=large >}}"
        href: https://orcid.org/0000-0002-4146-7083
      - text: "{{< iconify fa6-brands google-scholar size=large >}}"
        href: https://scholar.google.com.au/citations?user=NxovQdsAAAAJ&hl=en