---
title: "CV"
page-layout: full
block-banner: true
format: 
  html:
    css: styles.css
toc: true
toc-location: left
filters:
  - bibs/multiple-bibliographies.lua
csl: bibs/apa-cv.csl
bibliography_journals: bibs/journals.bib
bibliography_conferences: bibs/conferences.bib
bibliography_reports: bibs/reports.bib
bibliography_other: bibs/other.bib
nocite: |
  @*
---

### EDUCATION

#### **Master of Philosophy (Research)** \| QUT \| 2017 -- 2021

-   Thesis: [Phylosymbiosis and the microbiome of the native Australian stingless bee *Tetragonula carbonaria*](https://eprints.qut.edu.au/212693/)
-   Supervisors: Associate Professor Caroline Hauxwell, Professor James McGree

#### **Bachelor of Science (Chemistry)** \| QUT \| 2014 -- 2016

-   Graduated with Distinction

### RESEARCH EXPERIENCE

<ul class="accordion">
<li>
<input type="radio" name="accordion" id="zeroth" checked>
<label for="zeroth"><span class = "exptitle"><span class = "left">Senior Data Analyst | DPI</span><span class = "right">Sep 2023 -- Present</span></span></label>
<div class="content">
Use data science to deliver fresher produce.
</div>
</li>
<li>
<input type="radio" name="accordion" id="first">
<label for="first"><span class = "exptitle"><span class = "left">Senior Research Assistant | QUT</span><span class = "right">Jan 2022 -- Jul 2023</span></span></label>
<div class="content">
Managed data curation, exploration, visualisation, and modelling across four 
separate projects. Analysed 16S metabarcoding data to investigate microbial 
markers of pasture dieback. Modelled diurnal fluctuations in bee hive 
temperature to isolate the relationship between colony strength and temperature 
regulation. Trained students and junior research assistants in the use of HPC 
infrastructure for bioinformatics.
</div>
</li>
<li>
<input type="radio" name="accordion" id="second">
<label for="second"><span class = "exptitle"><span class = "left">Research Assistant | QUT</span><span class = "right">Mar 2020 -- Jan 2022</span></span></label>
<div class="content">
Modelled the influence of bee colony strength on hive temperature. Used GC-MS 
and SIFT-MS methods to identify volatile compounds associated with 
mealybug-induced pasture dieback.
</div>
</li>
<li>
<input type="radio" name="accordion" id="third">
<label for="third"><span class = "exptitle"><span class = "left">Graduate Student | QUT</span><span class = "right">Feb 2017 -- Oct 2020</span></span></label>
<div class="content">
Investigated patterns of phylosymbiosis in the microbiome of a native Australian stingless bee (Tetragonula carbonaria). Provided bioinformatics and statistics expertise on 
collaborative projects.
</div>
</li>
<li>
<input type="radio" name="accordion" id="fourth">
<label for="fourth"><span class = "exptitle"><span class = "left">Visiting Graduate Student | BOKU</span><span class = "right">Oct 2018 -- Nov 2019</span></span></label>
<div class="content">
Developed tools for reproducible metabolomics research in R.
</div>
</li>
<li>
<input type="radio" name="accordion" id="fifth">
<label for="fifth"><span class = "exptitle"><span class = "left">Technical Assistant | QUT</span><span class = "right">Feb 2016 -- Dec 2017</span></span></label>
<div class="content">
Contributed to collaborative projects developing fungal and viral biocontrol 
agents to manage invasive insect species. Maintained insect colonies, 
assisted with bioassays, cultured microorganisms, and used molecular techniques 
including PCR and gel electrophoresis.
</div>
</li>
<li>
<input type="radio" name="accordion" id="sixth">
<label for="sixth"><span class = "exptitle"><span class = "left">Vacation Research Student | QUT</span><span class = "right">Nov 2016 -- Feb 2017, Nov 2015 -- Feb 2016</span></span></label>
<div class="content">
Optimised and benchmarked open source and in-house amplicon metabarcoding 
pipelines. Automated video processing of behavioural assays and applied GC-MS 
technology to investigate the effects of fungal volatiles on beetle behaviour.
</div>
</li>
</ul>

### PUBLICATIONS

<ul class="accordion">
<li>
<input type="radio" name="accordion" id="a">
<label for="a"><span class = "exptitle"><left>Journal Articles</left></span></label>
<div class="content">
::: {#refs_journals}
:::
</div>
</li>
<li>
<input type="radio" name="accordion" id="b">
<label for="b"><span class = "exptitle"><left>Posters and Conference Presentations</left></span></label>
<div class="content">
::: {#refs_conferences}
:::
</div>
</li>
<li>
<input type="radio" name="accordion" id="c">
<label for="c"><span class = "exptitle"><left>Industry Reports</left></span></label>
<div class="content">
::: {#refs_reports}
:::
</div>
</li>

<li>
<input type="radio" name="accordion" id="d">
<label for="d"><span class = "exptitle"><left>Other Publications</left></span></label>
<div class="content">
::: {#refs_other}
:::
</div>
</li>

</ul>

### AWARDS AND SCHOLARSHIPS

-   **RSEAA22 Unconference Scholarship** (2022)
-   **First Place, SIP Student Poster Award** (2018)
-   **Endeavour Postgraduate Scholarship** (2018)
-   **QUT Vacation Research Experience Scholarship (x2)** (2015, 2016)
-   **QUT College of Excellence** (2016)
-   **Dean's List, QUT Science and Engineering Faculty** (Semester One, 2014)

### OTHER EXPERIENCE

<ul class="accordion">

<li>
<input type="radio" name="accordion" id="negativeone-a">
<label for="negativeone-a"><span class = "exptitle"><span class = "left">Justice of the Peace (Qualified)</span><span class = "right">Nov 2023 -- Present</span></span></label>
<div class="content">
Performing JP duties, including acting as an after-hours JP.
</div>
</li>

<li>
<input type="radio" name="accordion" id="first-a">
<label for="first-a"><span class = "exptitle"><span class = "left">Change Champion | QUT</span><span class = "right">May 2022 - Jun 2023</span></span></label>
<div class="content">
A service role supporting the rollout of new HR software in the Faculty of 
Science.
</div>
</li>

<li>
<input type="radio" name="accordion" id="zeroth-a">
<label for="zeroth-a"><span class = "exptitle"><span class = "left">Future Foods Datathon Mentor | QUT</span><span class = "right">August 2022 - Nov 2022</span></span></label>
<div class="content">
Mentored two teams, both of which won $20,000 in funding.
</div>
</li>
 
<li>
<input type="radio" name="accordion" id="third-a">
<label for="third-a"><span class = "exptitle"><span class = "left">AusSynBio Challenge Mentor | QUT</span><span class = "right">March 2022 -- Oct 2022</span></span></label>
<div class="content">

</div>
</li>

<li>
<input type="radio" name="accordion" id="fourth-a">
<label for="fourth-a"><span class = "exptitle"><span class = "left">Lab Demonstrator | QUT</span><span class = "right">Feb 2022 -- June 2022 </span></span></label>
<div class="content">
Also Feb 2021 -- May 2021, Feb 2020 -- May 2020, Feb 2018 -- May 2018, 
and Feb 2017 -- May 2017.

Mentored small groups of undergraduates through lab work and data analysis in a 
research-based environmental microbiology subject. Supported the transition to 
online teaching during the COVID-19 pandemic by developing new course materials. 
Assessed weekly lab reports and final poster presentations.
</div>
</li>

<li>
<input type="radio" name="accordion" id="fifth-a">
<label for="fifth-a"><span class = "exptitle"><span class = "left">SEF Widening Participation Senior Ambassador | QUT</span><span class = "right">Jul 2018 -- Sep 2018</span></span></label>
<div class="content">
Delivered engaging presentations and hands-on science workshops to school 
students, promoting diversity and higher education in STEM fields. Supervised 
and trained junior ambassadors.
</div>
</li>

<li>
<input type="radio" name="accordion" id="sixth-a">
<label for="sixth-a"><span class = "exptitle"><span class = "left">SEF Widening Participation Ambassador | QUT</span><span class = "right">Feb 2018 -- Jul 2018</span></span></label>
<div class="content">
</div>
</li>
 
<li>
<input type="radio" name="accordion" id="seventh-a">
<label for="seventh-a"><span class = "exptitle"><span class = "left">Note-taker | QUT</span><span class = "right">Feb 2014 -- Nov 2016</span></span></label>
<div class="content">
Supported Equity Services at QUT by delivering thorough summaries of lectures, 
tutorials, and labs.
</div>
</li>

<li>
<input type="radio" name="accordion" id="eighth-a">
<label for="eighth-a"><span class = "exptitle"><span class = "left">Connect Session Facilitator | QUT</span><span class = "right">2015 -- 2016</span></span></label>
<div class="content">
</div>
</li>

</ul>

### MEMBERSHIPS

|                                                      |                       |                      |
|------------------------|------------------------|------------------------|
| **Australia Global Alumni**                          | Member                | Dec 2019 -- Present  |
| **Higher Education Academy**                         | Associate Fellow      | Jul 2018 -- Present  |
| **QUT SEF HDR Student Society Organising Committee** | Member                | Jun 2018 -- Sep 2018 |
<!-- | **Society for Invertebrate Pathology**               | Member                | X - Present          | -->
<!-- |                                                      | Student Member        | May 2018 -- X        | -->

